spring:
  cloud:
    stream:
      bindings:
        #生产者绑定，消息通道name
        testQueue:
          # #exchange名称，交换模式默认是topic
          destination: testQueue
          binder: testBinder
      rabbit:
        bindings:
          #===============新增============#
          testQueue:
            producer:
              routing-key-expression: '''test'''
      binders:
        testBinder:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                username: test
                password: 123456
                host: 192.168.10.22
                port: 5672
                virtual-host: /test
